male(karim).
male(rahim).
male(raju).
male(jimi).
female(jamila).
female(setu).
female(rakhi).
parents(karim,rahim).
parents(jamila,rahim).
parents(jamila,setu).
parents(rahim,raju).
parents(rahim,rakhi).
parents(rakhi,jimi).
parents(raju,joy).
father(X,Y):-
male(X),parents(X,Y).
mother(X,Y):-
female(X),parents(X,Y).
haschild(X):-
parents(X,_).
son(X,Y):-
male(X),parents(Y,X).
daughter(X,Y):-
female(X),parents(Y,X).
brother(X,Y):-
male(X),parents(Z,X),parents(Z,Y),X\=Y.
sister(X,Y):-
female(X),parents(Z,X),parents(Z,Y),X\=Y.
grandfather(X,Y):-
male(X),parents(X,Someone),parents(Someone,Y).
grandmother(X,Y):-
female(X),parents(X,Someone),parents(Someone,Y).
uncle(X,Y):-
male(X),brother(X,Someone),parents(Someone,Y),X\=Y.
aunt(X,Y):-
female(X),sister(X,Someone),parents(Someone,Y),X\=Y.
cousin(X,Y):-
parents(Someone,X),parents(Somebody,Y),brother(Someone,Somebody),X\=Y.
cousin(X,Y):-
parents(Someone,X),parents(Somebody,Y),sister(Someone,Somebody),X\=Y.